#!/bin/bash

load inquirer

check() {
  config::load_file $SERVICE_MYSQL_CONFIG

  if [ -z "$SERVICE_MYSQL_HOST" ]; then
    inquirer::text "请输入 SERVICE_MYSQL_HOST:" value
    config::set SERVICE_MYSQL_HOST $value $SERVICE_MYSQL_CONFIG
  fi

  if [ -z "$SERVICE_MYSQL_PORT" ]; then
    inquirer::text "请输入 SERVICE_MYSQL_PORT:" value
    config::set SERVICE_MYSQL_PORT $value $SERVICE_MYSQL_CONFIG
  fi

  if [ -z "$SERVICE_MYSQL_ROOT_PASSWORD" ]; then
    inquirer::text "请输入 SERVICE_MYSQL_ROOT_PASSWORD:" value
    config::set SERVICE_MYSQL_ROOT_PASSWORD $value $SERVICE_MYSQL_CONFIG
  fi

  if [ -z "$SERVICE_MYSQL_USERNAME" ]; then
    inquirer::text "请输入 SERVICE_MYSQL_USERNAME:" value
    config::set SERVICE_MYSQL_USERNAME $value $SERVICE_MYSQL_CONFIG
  fi

  if [ -z "$SERVICE_MYSQL_PASSWORD" ]; then
    inquirer::text "请输入 SERVICE_MYSQL_PASSWORD:" value "$(os::uuid)"
    config::set SERVICE_MYSQL_PASSWORD $value $SERVICE_MYSQL_CONFIG
  fi

  if [ -z "$SERVICE_MYSQL_DATABASE" ]; then
    inquirer::text "请输入 SERVICE_MYSQL_DATABASE:" value
    config::set SERVICE_MYSQL_DATABASE $value $SERVICE_MYSQL_CONFIG
  fi
  
  # @TODO load again
  config::load_file $SERVICE_MYSQL_CONFIG

  # @TODO
  export SERVICE_MYSQL_HOST=$SERVICE_MYSQL_HOST
  export SERVICE_MYSQL_PORT=$SERVICE_MYSQL_PORT
  export SERVICE_MYSQL_ROOT_PASSWORD=$SERVICE_MYSQL_ROOT_PASSWORD
  export SERVICE_MYSQL_USERNAME=$SERVICE_MYSQL_USERNAME
  export SERVICE_MYSQL_PASSWORD=$SERVICE_MYSQL_PASSWORD
  export SERVICE_MYSQL_DATABASE=$SERVICE_MYSQL_DATABASE
}

check $@
