#!/bin/bash

load inquirer

check() {
  if [ ! -f "$SERVICE_MYSQL_MY_CNF" ]; then
    cp $SERVICE_DIR/default/my.cnf $SERVICE_MYSQL_MY_CNF
  fi

  service::config SERVICE_MYSQL_HOST text "Input SERVICE_MYSQL_HOST:"
  service::config SERVICE_MYSQL_PORT text "Input SERVICE_MYSQL_PORT:"
  service::config SERVICE_MYSQL_ROOT_PASSWORD text "Input SERVICE_MYSQL_ROOT_PASSWORD:" $(os::random_string 16)
  service::config SERVICE_MYSQL_USERNAME text "Input SERVICE_MYSQL_USERNAME:" $(os::random_string 4)
  service::config SERVICE_MYSQL_PASSWORD text "Input SERVICE_MYSQL_PASSWORD:" $(os::random_string 8)
  service::config SERVICE_MYSQL_DATABASE text "Input SERVICE_MYSQL_DATABASE:" $(os::random_string 4)
}

check $@
