version: '3.7'

services:
  mysql:
    restart: always
    image: whatwewant/mysql:${SERVICE_MYSQL_VERSION}
    # platform: linux/x86_64
    ports:
      - ${SERVICE_MYSQL_HOST}:${SERVICE_MYSQL_PORT}:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${SERVICE_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${SERVICE_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${SERVICE_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${SERVICE_MYSQL_DATABASE}
    volumes:
      - ${SERVICE_DATA}:/var/lib/mysql


networks:
  default:
    external: true
    name: compose-ingress
