version: '3.7'

services:
  mysql:
    restart: always
    image: ${SERVICE_IMAGE_REGISTRY}/whatwewant/mysql:${SERVICE_MYSQL_VERSION}
    # platform: linux/x86_64
    ports:
      - ${SERVICE_MYSQL_HOST}:${SERVICE_MYSQL_PORT}:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${SERVICE_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${SERVICE_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${SERVICE_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${SERVICE_MYSQL_DATABASE}
    volumes:
      # conf
      # - ${SERVICE_CONFIGS}/conf:/etc/mysql/conf.d
      - ${SERVICE_MYSQL_MY_CNF}:/etc/mysql/my.cnf
      # data
      - ${SERVICE_DATA}:/var/lib/mysql
    mem_limit: 8192m
    cpus: 4
    # fix "mbind: Operation not permitted"
    # stackoverflow: https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
    cap_add:
      - SYS_NICE

networks:
  default:
    external: true
    name: compose-ingress
